AllCops:
    TargetRubyVersion: 2.4
    UseCache: true
    CacheRootDirectory: '/home/daniel/.cache'
    AllowSymlinksInCacheRootDirectory: true

Metrics:
    LineLength:
        IgnoredPatterns: []

Style/FrozenStringLiteralComment:
    Enabled: false
Style/PercentLiteralDelimiters:
    PreferredDelimiters:
        "%w": "[]"
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma
Style/WordArray:
    Enabled: false
