AllCops:
    TargetRubyVersion: 2.3
    UseCache: true
    CacheRootDirectory: '/home/daniel/.cache'

Style/FrozenStringLiteralComment:
    Enabled: false
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma
Style/WordArray:
    Enabled: false
