AllCops:
    TargetRubyVersion: 2.4
    UseCache: true
    CacheRootDirectory: '/home/daniel/.cache'
    AllowSymlinksInCacheRootDirectory: true

Layout:
    ConditionPosition: true
    SpaceInsideHashLiteralBraces:
        EnforcedStyle: no_space

Lint:
    IneffectiveAccessModifier:
        Enabled: false

Metrics:
    LineLength:
        IgnoredPatterns: []

Style:
    RegexpLiteral:
        EnforcedStyle: slashes
        AllowInnerSlashes: true
    FrozenStringLiteralComment:
        Enabled: when_needed
Style/PercentLiteralDelimiters:
    PreferredDelimiters:
        "%w": "[]"
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma
Style/WordArray:
    Enabled: false
